### ISSUE TITLE
Object not found!

### ISSUE THREAD

**Issue by boualimed** [SUPLA/supla-cloud#168] opened 2017-12-03 20:44 UTC
supla-cloud dev mode : 
Error 404 - Object not found! when logging with user@supla.org "The requested URL was not found on this server..."
xampp V3.2.2

**Comment by fracz** [comment] 2017-12-03 21:43
Have you started the webpack dev server? https://github.com/SUPLA/supla-cloud/blob/master/Development.md#development

**Comment by boualimed** [comment] 2017-12-04 09:47
Thank you for your reply,
Yes, it's running at  https://localhost:25787/ but no change, for example, I have tried to put the URL route manually it's worked just for this specified URL.

**Comment by fracz** [comment] 2017-12-04 09:48
Try disabling the `https` by adding a `supla_protocol: http` to your `app/config/parameters.yml`.

**Comment by boualimed** [comment] 2017-12-04 10:06
No the same problem, but the previous version of supla is working fine.

**Comment by fracz** [comment] 2017-12-04 10:32
Have you downloaded new dependencies after upgrade from previous version with `composer install`? Which version it was?

**Comment by boualimed** [comment] 2017-12-04 10:43
when I run composer install `supla_protocol: http `automatically deleted from parameters.yml and it hasn't accepted.

**Comment by boualimed** [comment] 2017-12-04 12:18
using unix is better than xampp.

**Comment by boualimed** [comment] 2017-12-04 19:22
Hello fracz, 

I got these errors while deploying supla on Unix(Ubuntu), 

`ERROR`     [console] Error thrown while running command "supla:dev:dropAndLoadFixtures -e dev". Message: "An exception occurred while executing 'INSERT INTO supla_dev_channel (channel_number, caption, type, func, flist, param1, param2, param3, alt_icon, hidden, iodevice_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, null, 2900, 140, null, "", "", "", 0, 0, 1, 1]:


Command "supla:dev:dropAndLoadFixtures -e dev" exited with code "1" ["command" => "supla:dev:dropAndLoadFixtures -e dev","code" => 1] []

An exception occured in driver:` SQLSTATE[HY000] [1049]` Unknown database 'supla' in /var/www/supla/src/SuplaApiBundle/Resources/config/routing.yml (which is being imported from "/var/www/supla/app/config/routing.yml"). Make sure there is a loader supporting the "rest" type.

**Comment by fracz** [comment] 2017-12-05 10:34
Try the following:

1. Install new deps with `composer install`
1. Clear the cache `rm -fr var/cache/*`
1. Clear and refill the database with the command you have tried already

And, keep in mind that the `master` is not meant to be stable (although the error you posted indicate problem with deps or cache). If you want a stable version, try checking out the commit marked as the latest release: https://github.com/SUPLA/supla-cloud/releases

**Comment by boualimed** [comment] 2017-12-05 11:33
Very helpful, it's working now thank you.

another not fixed issue:
- [ ] in Node server the command ` npm run dev` not seen from the outside with `https://localhost:25787`

    Loading...
if it takes too long, check if the JS scripts are loaded correctly/

**Comment by fracz** [comment] 2017-12-05 14:31
Again, try disabling the https by adding a `supla_protocol: http` to your `app/config/parameters.yml` and then remove the cache `rm -fr var/cache/*`.

I were not aware that `composer install` may delete the custom parameter from there. Will try to investigate why it happens.

**Comment by boualimed** [comment] 2017-12-06 08:35
About the option `supla_protocol: http`, as I expected has been ignored from `parameters.yml` after hitting `composer install `.(i've added it in the last, directly after the `secret: ...` option). even after cleaning the cache by `rm -fr var/cache/*.`
Supla cloud now perfectly running on VM ubuntu OS guest. but, the webpack not loading to the host it shows the same **loading Alert.**

**Comment by fracz** [comment] 2017-12-06 14:46
In chrome/firefox hit the <kbd>F12</kbd> and reload the page. The network tab should give you a hint why it cannot load the scripts from webpack.

**Comment by boualimed** [comment] 2017-12-06 17:26
Look what i'm getting from Console:
 `GET http://localhost:25787/assets/dist/commons.js net::ERR_CONNECTION_REFUSED`
 `GET http://localhost:25787/assets/dist/translations/messages-en.js net::ERR_CONNECTION_REFUSED`
**Uncaught ReferenceError: jQuery is not defined**.  
(anonymous) @ login:115
`login:199 GET http://localhost:25787/assets/dist/login-page.js net::ERR_CONNECTION_REFUSED`

**Comment by fracz** [comment] 2017-12-07 22:19
Ok, I have chekced why the `supla_protocol: http` is being removed from the `parameters.yml` and indeed, it is an expected behavior. This setting is provided in `config_dev.yml` so if you have dev environment enabled - you are good to go without this line in your `parameters.yml`.

As for the errors you have posted now: they're strage. Can you access the `http://localhost:25787/assets/dist/commons.js` directly after launching webpack dev server? If no, what is the error?

Also, I have faced an insane problem today with Google Chrome - [it adds a HSTS (SSL requirement) for all domains ending with `.dev`](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/). Therefore, it forces the `supla.dev` site to work over ssl, ignoring the application settings. If this is your case, it may cause the `CONNECTION_REFUSED` errors because it is forbidden to load HTTP content into HTTPS-enabled website. The solution is to change `supla.dev` to something else, not "auto-secured" by Chrome. I have just updated the [development docs](https://github.com/SUPLA/supla-cloud/blob/master/Development.md) with a suggestion of `supla.local`.

Hope you will be able to run SUPLA now :-)

**Comment by boualimed** [comment] 2017-12-08 10:31
As I said before `supla-cloud` perfectly works for me in local machine with zero errors, but the access form the host is refused even from the others devices. as well with others browsers, nothing has changed.
I have modified the hosts in `/etc/hosts` and i've tried with `0.0.0.0`.....,. in addition the ufw is disabled. and restarted apache with many different configurations also.
I think the problem has occurred with Node js configuration. 
[https://superuser.com/questions/448941/accessing-ubuntu-guest-virtualbox-node-js-server-from-windows-host](url)
[https://github.com/angular/angular-cli/issues/1793](url)
About supla.dev I have used many VirtualHost names in apache .dev/.local/ no problem with it.  
Thank you for your support. 

**Just look at these attachments, might help you to find the mistake:**

- 

 
- ![screenshot 6](https://user-images.githubusercontent.com/12487239/33761173-67e0d4a6-dc08-11e7-835a-392bcf724073.png)
- ![screenshot 7](https://user-images.githubusercontent.com/12487239/33761174-67fba5d8-dc08-11e7-99df-14a08e04cd69.png)
- ![screenshot 8](https://user-images.githubusercontent.com/12487239/33761175-6815ac08-dc08-11e7-90e8-d73820081143.png)
- ![screenshot 9](https://user-images.githubusercontent.com/12487239/33761176-6833e7ae-dc08-11e7-964f-186c97ce9c6b.png)
- ![screenshot 10](https://user-images.githubusercontent.com/12487239/33761177-68537678-dc08-11e7-9cea-9d2cdca88b87.png)
- ![screenshot 11](https://user-images.githubusercontent.com/12487239/33761181-695c4716-dc08-11e7-911c-a5191a154ceb.png)
- ![screenshot 12](https://user-images.githubusercontent.com/12487239/33761182-6a17df8a-dc08-11e7-8736-8f68ac449ee6.png)
- ![screenshot 13](https://user-images.githubusercontent.com/12487239/33761183-6a6d841c-dc08-11e7-92b5-d1a6ff5aba52.png)
-

**Comment by fracz** [comment] 2018-02-24 17:46
Have you solved the problem?

**Comment by boualimed** [comment] 2018-02-26 08:18
I don't know exactly why this problem is happening. but i've tried the installation on two PC and it worked at the other, in case that the front-end is running in the second(the first pc detect the http://localhost.....from the second pc), and vice versa, so are not being independent of each other.
Thank you in advance.

**Comment by fracz** [comment] 2018-03-29 14:32
Please try with new `master` branch. A lot has changed and we are about to launch v2.2. If the problem is still valid, please reopen. Thank you!

**Closed by fracz** 2018-03-29 14:32 UTC
